### ISSUE TITLE
Auth: Login/pasword protection

### ISSUE THREAD

**Issue by olehkrupko** [olehkrupko/swamp-api#6]
Front-End: https://github.com/olehkrupko/swamp-subscriptions/issues/85

# Tasks
- [x] Submit username & password to API
- [x] Accept them in API
- [x] Return token
- [x] Save token on Front-end
- [x] Add admin-only as a dependancy
- [ ] Add renew token
- [ ] Auto-renew access token
- [ ] Don't send credentials on non-https
